name: Feature Request
description: Suggest a feature or enhancement for the project
title: "[FEATURE] "
labels: [enhancement]
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request! Please answer the following questions to help us better understand your request.

  - type: input
    id: feature_name
    attributes:
      label: "Feature Name"
      description: "Provide a brief name for the feature request."
      placeholder: "e.g. Dark Mode Toggle"
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem Statement"
      description: "Describe the problem or challenge that this feature would solve."
      placeholder: "What is the current situation or problem that this feature would address?"
    validations:
      required: true

  - type: textarea
    id: solution_description
    attributes:
      label: "Describe the solution you'd like"
      description: "Give a clear and concise description of what you want to happen."
      placeholder: "e.g. Adding a dark mode toggle to the settings menu."
    validations:
      required: true
